[debug] [2019-03-08T13:33:42.769Z] ----------------------------------------------------------------------
[debug] [2019-03-08T13:33:42.771Z] Command:       D:\WEB\node-v8.9.4-win-x64\node.exe D:\WEB\node-v8.9.4-win-x64\node_modules\firebase-tools\bin\firebase login --reauth
[debug] [2019-03-08T13:33:42.771Z] CLI Version:   4.2.1
[debug] [2019-03-08T13:33:42.771Z] Platform:      win32
[debug] [2019-03-08T13:33:42.772Z] Node Version:  v8.9.4
[debug] [2019-03-08T13:33:42.772Z] Time:          Fri Mar 08 2019 10:33:42 GMT-0300 (Hora oficial do Brasil)
[debug] [2019-03-08T13:33:42.772Z] ----------------------------------------------------------------------
[debug] 
[info] 
[info] Visit this URL on any device to log in:
[info] https://accounts.google.com/o/oauth2/auth?client_id=563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com&scope=email%20openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform&response_type=code&state=638548600&redirect_uri=http%3A%2F%2Flocalhost%3A9005
[info] 
[info] Waiting for authentication...
[debug] [2019-03-08T13:33:56.261Z] >>> HTTP REQUEST POST https://accounts.google.com/o/oauth2/token  

[debug] [2019-03-08T13:33:56.739Z] Token Fetch Error: Error
    at new FirebaseError (D:\WEB\node-v8.9.4-win-x64\node_modules\firebase-tools\lib\error.js:11:16)
    at Request._callback (D:\WEB\node-v8.9.4-win-x64\node_modules\firebase-tools\lib\api.js:34:11)
    at self.callback (D:\WEB\node-v8.9.4-win-x64\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (D:\WEB\node-v8.9.4-win-x64\node_modules\firebase-tools\node_modules\request\request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
